docs: add tutor compatibility notes
overhangio/tutor pull request #1122
Opened 2024-09-18 16:06 UTC by MaferMazu

## Description

This PR adds the compatibility notes in the README. Also, it adds information on the initial page for documentation and is referenced on the installation process page.

## How to test

2024-09-18 17:06 UTC, MaferMazu commented
@kdmccormick @regisb @sarina, could you help me review this PR?

2024-09-19 07:52 UTC, regisb commented on changelog.d/20240918_121327_maria.magallanes_docs_tutor_version.md
> +[Documentation] Add compatibility notes, so you find info about what version of Tutor you should install by the Open edX release you need. (by @MaferMazu)
This entry is unnecessary for documentation changes: https://docs.tutor.edly.io/tutor.html#contributing

2024-09-19 23:07 UTC, MaferMazu commented
I applied the feedback.

If you have more feedback, please let me know.

Screenshot
![image](https://github.com/user-attachments/assets/e26799ba-72a4-4dd8-9dd2-3ab1af8607b7)

2024-09-20 12:09 UTC, regisb requested changes

2024-09-20 12:09 UTC, regisb commented on README.rst
> +.. _compatibility_notes_start:
I'd rather not include these compatibility notes in the README, nor in the documentation frontpage. That information belongs only in the install docs.

2024-09-23 22:50 UTC, MaferMazu commented
Thanks for the feedback, @regisb. I have already applied it.

2024-09-24 07:22 UTC, regisb approved these changes
Thanks for the quick updates and for bearing with me :)

2024-09-24 07:22 UTC, merged