docs: New config value FORUM_MONGODB_DATABASE added in docs
overhangio/tutor pull request #455
Opened 2021-06-18 00:08 UTC by ChrisChV

- New config value `FORUM_MONGODB_DATABASE` added in docs referencing to https://github.com/overhangio/tutor/pull/453

2021-06-18 07:29 UTC, regisb requested changes

2021-06-18 07:29 UTC, regisb commented on docs/configuration.rst
> +- ``FORUM_MONGODB_DATABASE`` (default: ``cs_comments_service``)
Can you also please add the ``RUN_FORUM`` and ``FORUM_HOST`` variables?

2021-06-22 07:47 UTC, regisb commented on docs/configuration.rst
> +- ``FORUM_MONGODB_DATABASE`` (default: ``cs_comments_service``)
Sorry to nitpick @ChrisChV, but could you add "" quotes around the values for `FORUM_HOST` and `FORUM_MONGODB_DATABASE`? This is to indicate that the type of the setting value is a string, as for other items in the docs. Thus:

```
- ``RUN_FORUM`` (default: ``true``)
- ``FORUM_HOST`` (default: ``"forum"``)
- ``FORUM_MONGODB_DATABASE`` (default: ``"cs_comments_service"``)
```

2021-06-22 20:13 UTC, ChrisChV commented
Ok @regisb, I think it's done

2021-06-22 22:51 UTC, regisb approved these changes

2021-06-22 22:51 UTC, merged

2021-06-22 22:51 UTC, regisb commented
Thanks @ChrisChV!