docs: fix links kubectl docs
overhangio/tutor pull request #482
Opened 2021-09-02 12:41 UTC by regisb

Previous links resulted in 404.

Close #479.

This is ready for review @overhangio/tutor-developers. Cc @0x29a who opened #479.

2021-09-02 13:29 UTC, 0x29a requested changes
@regisb, thanks for fixing this.

I see one more dead link:
```
➜  tutor git:(regisb/fix-kubectl-docs) rg "https://kubectl.docs.kubernetes.io/pages"
docs/k8s.rst
70:To learn more about "kustomizations", refer to the `official documentation <https://kubectl.docs.kubernetes.io/pages/app_customization/introduction.html>`__.
```

2021-09-02 13:29 UTC, 0x29a commented on docs/k8s.rst
> +Basically, the whole platform is described in manifest files stored in ``$(tutor config printroot)/env/k8s``. There is also a ``kustomization.yml`` file at the project root for `declarative applicati
Is `declarative application management` a one-off hyperlink? If so, double underscore should be used.

2021-09-06 07:44 UTC, regisb commented
Thanks for the comments @0x29a! This is ready for review again.

2021-09-06 09:30 UTC, 0x29a approved these changes
Thanks!

2021-09-06 10:40 UTC, merged