improvement: add var `PREVIEW_LMS_BASE`
overhangio/tutor pull request #502
Opened 2021-09-29 12:30 UTC by iamCristYe

discussion here: https://discuss.overhang.io/t/new-settings-variable/1973/4

If my interpretation of https://github.com/overhangio/tutor/blob/926263deb31fab0fe28c1046fd6649e8be31fecd/tutor/config.py#L47 is correct, current users will not need to manually add the new variable for preview domain to work, as missing this config yaml will lead tutor to use the default value.

2021-09-30 10:47 UTC, regisb requested changes

2021-09-30 10:47 UTC, regisb commented on tutor/interactive.py
> +            "PREVIEW_LMS_HOST": "preview.local.overhang.io",
I would rather avoid adding an extra question to the quickstart. I think that the default value is reasonable for most people, and we don't need to ask everyone about it.

2021-09-30 10:47 UTC, regisb commented on CHANGELOG.md
> +- [Improvement] Add variable `PREVIEW_LMS_BASE` for custom preview domain.
Please replace "variable" by "configuration setting".

2021-09-30 10:48 UTC, regisb requested changes

2021-09-30 10:48 UTC, regisb commented on CHANGELOG.md
> +- [Improvement] Add variable `PREVIEW_LMS_BASE` for custom preview domain.
Also, this is actually a new feature, so you can replace "Improvement" by "Feature". Please also amend the git commit title accordingly.

2021-09-30 10:49 UTC, regisb commented
Can you please add the discussion link to the git commit message, such that people don't have to research this PR later?

2021-10-01 01:52 UTC, iamCristYe commented
@regisb Please check if it's good for merge now 😊

2021-10-04 08:23 UTC, regisb requested changes

2021-10-04 08:23 UTC, regisb commented on tutor/interactive.py
> -        )
This part of the file should not be modified.

2021-10-04 12:51 UTC, merged

2021-10-04 12:51 UTC, regisb commented
Thanks again for your PR @iamCristYe!