Tutorial: how to run Tutor on ARM-based systems
overhangio/tutor pull request #549
Opened 2021-12-15 20:22 UTC by bradenmacdonald

Per the discussion on https://github.com/overhangio/tutor/issues/510 and https://github.com/overhangio/tutor/pull/543, here is a tutorial for the docs that explains how to run Tutor on ARM-based systems like M1 MacBooks.

I wasn't sure exactly where to put it, so let me know if it should be moved somewhere else.

Screenshot:
<img width="1101" alt="Screen Shot 2021-12-15 at 12 21 50 PM" src="https://user-images.githubusercontent.com/945577/146259440-571a7f96-12ad-4331-a232-4b87293d4d1d.png">

2021-12-20 14:38 UTC, regisb requested changes
Thanks for your PR Braden! Let's take the time to a few minor changes and we'll merge this after the Maple release.

2021-12-20 14:38 UTC, regisb commented on docs/tutorials/arm64.rst
> +Running Tutor on ARM based Systems
nit: "ARM-based systems"

2021-12-20 14:38 UTC, regisb commented on docs/tutorials/arm64.rst
> +Start by :ref:`installing <install>` Tutor and its depdencies (e.g. Docker) onto your system.
dependencies

2021-12-20 14:38 UTC, regisb commented on docs/tutorials/arm64.rst
> +    tutor images build openedx-dev
This is going to change in Maple and become: `tutor dev dc build lms`.

2021-12-20 20:28 UTC, bradenmacdonald commented
You're welcome @regisb. Thanks for the review. I've addressed all the comments.

2022-01-03 05:56 UTC, regisb approved these changes

2022-01-03 05:56 UTC, merged

2022-01-03 05:57 UTC, regisb commented
Thanks for taking the time to write this tutorial @bradenmacdonald, much appreciated.

2022-01-03 18:27 UTC, bradenmacdonald commented
You're welcome @regisb. Cheers.