fix: Patch issue on Dockerfile missplaced
overhangio/tutor pull request #598
Opened 2022-02-26 13:55 UTC by CodeWithEmad

it's the fix for issue https://github.com/overhangio/tutor/issues/597

2022-03-02 14:32 UTC, regisb requested changes
Moving the patch is not acceptable, as it would break backward compatibility. See my comment for alternative solutions.

2022-03-05 06:18 UTC, CodeWithEmad commented on tutor/templates/build/openedx/Dockerfile
> +{{ patch("openedx-dockerfile") }}
Awesome solutions @regisb, like always. thanks for your time and effort put in the Tutor project

2022-03-05 06:18 UTC, closed without merging

2022-03-10 18:27 UTC, regisb commented on tutor/templates/build/openedx/Dockerfile
> +{{ patch("openedx-dockerfile") }}
Will you open a PR to add a "openedx-dockerfile-minimal" patch?

2022-03-11 14:21 UTC, CodeWithEmad commented on tutor/templates/build/openedx/Dockerfile
> +{{ patch("openedx-dockerfile") }}
sure, on it :)

2022-03-11 14:27 UTC, CodeWithEmad commented on tutor/templates/build/openedx/Dockerfile
> +{{ patch("openedx-dockerfile") }}
please take a look at PR https://github.com/overhangio/tutor/pull/610