feat: configurable uwsgi buffer-size
overhangio/tutor pull request #612
Opened 2022-03-16 20:53 UTC by danielrudn

Building on the work done in https://github.com/overhangio/tutor/pull/427. This PR allows you to configure the uWSGI buffer size in `config.yml`

From the [uWSGI docs](https://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html):

> If you start receiving “invalid request block size” in your logs, it could mean you need a bigger buffer. Increase it (up to 65535) with the buffer-size option.

One of our deployments uses a SAML provider for authentication and we started receiving the `invalid request block size` error pretty frequently, so we bumped the buffer size to `32768`. Does it make sense to bump the default from `8192` to `32768` (or something else)?

2022-05-14 18:07 UTC, danielrudn commented
Hey @regisb , sorry for the delay! 

I don't think the SAML use-case would be too common, and this seems like an edge case since we did not encounter it for other Open edX deployments using SAML.

I've added the `{{ patch("openedx-dockerfile-final") }}` to the end of the openedx Dockerfile, this plugin code seems to work for updating overriding the CMD with a higher buffer-size flag:

```python
from tutor import hooks

hooks.Filters.ENV_PATCHES.add_item(
    (
        "openedx-dockerfile-final",
        """
CMD uwsgi \\
    --static-map /static=/openedx/staticfiles/ \\
    --static-map /media=/openedx/media/ \\
    --http 0.0.0.0:8000 \\
    --thunder-lock \\
    --single-interpreter \\
    --enable-threads \\
    --processes=${UWSGI_WORKERS:-2} \\
    --buffer-size=32768 \\
    --wsgi-file $SERVICE_VARIANT/wsgi.py
"""
    )
)
```

2022-05-16 14:44 UTC, regisb requested changes
Fix the docs, squash your commits and we'll be good to go :)

2022-05-16 14:44 UTC, regisb commented on docs/reference/patches.rst
> +======================
This is going to cause an error when building docs (`make docs`). The `===` line should be just as long as the title above.

2022-05-25 12:43 UTC, erickhgm commented
@danielrudn
Just to check, are you going to proceed with this feature?
It is useful to me, if it is no longer necessary for you, no worry. I can continue ...

2022-05-26 01:39 UTC, danielrudn commented
> @danielrudn Just to check, are you going to proceed with this feature? It is useful to me, if it is no longer necessary for you, no worry. I can continue ...

Yep, it should be good to go now.

2022-05-30 08:33 UTC, regisb approved these changes

2022-05-30 08:34 UTC, merged