feat: remove the implementation of dev runserver
overhangio/tutor pull request #710
Opened 2022-07-21 19:05 UTC by Carlos-Muniz

This PR removes the implementation of `tutor dev runserver`. It is being removed in favor of using `tutor dev start`.

This PR should be merged last after each of the following have been merged:

- https://github.com/overhangio/tutor-ecommerce/pull/31
- https://github.com/overhangio/tutor-forum/pull/8
- https://github.com/overhangio/tutor-notes/pull/13
- https://github.com/overhangio/tutor-xqueue/pull/9

Closes https://github.com/overhangio/2u-tutor-adoption/issues/26

2022-07-21 19:05 UTC, Carlos-Muniz commented
@kdmccormick @regisb This is ready for review.

2022-07-21 19:13 UTC, kdmccormick requested changes
Code changes look good, though you've got a linting error.

Make sure you add a CHANGELOG entry as described in the [contribution docs](https://docs.tutor.overhang.io/tutor.html?highlight=contrib#contributing-to-tutor).

2022-07-21 19:37 UTC, Carlos-Muniz commented
@kdmccormick I've addressed the linting error and added an entry to `CHANGELOG.md`

2022-07-21 19:44 UTC, kdmccormick commented
> Where “TYPE” is either “Bugfix”, “Improvement”, “Feature” or “Security”. You should add an explosion emoji (”💥”) before “[TYPE]” if you are making a breaking change.

This is a breaking change, and I think "Improvement" is the most appropriate type.

2022-07-21 19:53 UTC, Carlos-Muniz commented
@kdmccormick updated with your suggestion 👍

2022-07-21 19:53 UTC, kdmccormick approved these changes
LGTM

2022-07-25 13:36 UTC, regisb reviewed
I'd rather not make such breaking changes between two releases. I mean: sometimes we do make breaking changes between releases, but this one seems slightly too important for my taste. Plus, there is no rush to remove the `runserver` command, right? I think that the obsolete warning should be sufficient for now.

Do you think this PR could wait until Olive? Or maybe you can make this change on top of the nightly branch?

2022-07-25 13:47 UTC, kdmccormick commented
@regisb Carlos is just doing what we asked him to do :) From https://github.com/overhangio/2u-tutor-adoption/issues/26 :
> In order to give folks time to stop using runserver, wait until Tutor v14 is released.

But certainly, there's no rush on this. We could definitely wait until Olive or merge this to Nightly, whichever you prefer.

2022-08-30 17:27 UTC, kdmccormick commented
@regisb I've re-opened this PR on top of nightly: https://github.com/overhangio/tutor/pull/718

2022-08-30 17:27 UTC, closed without merging