Fix incorrect information about running config save --interactive
overhangio/tutor pull request #716
Opened 2022-08-10 23:43 UTC by frob

Running config save --interactive doesn't create a config.yml file in the current directory. It instead creates it in the project root.

2022-08-29 08:09 UTC, regisb commented on docs/local.rst
> +This is the only non-automatic step in the installation process. You will be asked various questions about your Open edX platform and appropriate configuration files will be generated. If you would l
Can you preserve this information?

> this file contains all the configuration values for your platform, such as randomly generated passwords, domain names, etc.

This link will not render correctly: `See (section above)[#tutor-root]`. You should use a `:ref:` -- see other places in the docs for reference. Please build the docs to check that your changes render correctly.

2022-08-29 08:09 UTC, regisb requested changes
Please build the docs to check that your changes render correctly.

2022-09-30 10:11 UTC, regisb commented
@frob just checking if you noticed by comment above?

2022-09-30 18:54 UTC, frob commented
I had not seen that. I will make the change shortly.

2022-09-30 19:33 UTC, frob commented
I made the requested changes. Unfortunately, I cannot build the docs with sphinx. I have installed the requirements from `requirements/docs.in` but I get this error:

```
File "/Users/fanderson/repos/edx/tutor/docs/../tutor/commands/cli.py", line 63, in ensure_plugins_enabled
    hooks.Actions.PROJECT_ROOT_READY.do(root=ctx.params["root"])
KeyError: 'root'
```

2022-09-30 19:44 UTC, frob commented
I deleted my venv and started fresh and now it builds. Fixed the typo `s/-/_`

2022-10-03 12:09 UTC, regisb approved these changes

2022-10-03 12:09 UTC, merged