feat: use encode gzip for caddy
overhangio/tutor pull request #735
Opened 2022-10-18 12:15 UTC by ghassanmas

Compressing assests would lead to readuce transfer size.
  As testing with frontend-app-learning/Olive, the network traffic
  before was about ~4MB, after this it became ~1MB.

  This change was suggested by Google Lighthouse[1], there are of
  course more suggestion but this was one the easiest and one of most
  impactful.

  Also check orignal PR overhangio/tutor-mfe/pull/64 for more
  info.
  [1]: https://web.dev/uses-text-compression

2022-10-18 12:27 UTC, regisb requested changes
Changelog!

2022-10-18 17:35 UTC, regisb requested changes
PLEASE TEST YOUR CHANGES! ALWAYS! this is breaking the Caddy config. The `encode gzip` directive should not be inside `reverse_proxy`.

2022-10-18 19:09 UTC, ghassanmas commented
Sorry about that, I was too confident!.
Now tha last change is tested on production and also using caddy cli, i.e. `caddy validate --config env/apps/caddy/Caddyfile`

2022-10-19 08:46 UTC, merged

2022-10-19 08:46 UTC, regisb approved these changes