refactor: change annotations to use built-in generic types
overhangio/tutor pull request #781
Opened 2023-01-10 18:15 UTC by Carlos-Muniz

Changes annotations from `typing` to use built-in generic types from `__future__.annotations`

Closes https://github.com/openedx/wg-developer-experience/issues/130

2023-01-10 21:01 UTC, Carlos-Muniz commented
@kdmccormick @regisb This is ready for review

2023-01-12 08:01 UTC, regisb requested changes
Looking good, thanks! Just a few minor comments.

2023-01-17 15:46 UTC, Carlos-Muniz commented on tests/test_plugins_v0.py
> +        overriden_items: list[tuple[str, t.Any]] = hooks.Filters.CONFIG_OVERRIDES.apply(
I'm not sure I understand. Do you want me to remove  `: list[tuple[str, t.Any]]` from line 201?

2023-01-17 16:54 UTC, Carlos-Muniz commented on tests/test_plugins_v0.py
> +        overriden_items: list[tuple[str, t.Any]] = hooks.Filters.CONFIG_OVERRIDES.apply(
Removed `: list[tuple[str, t.Any]]`

2023-01-17 17:02 UTC, Carlos-Muniz commented on tests/commands/test_compose.py
> +        compose_jobs_file: dict[
The mypy tests only pass if the type annotations are removed for both `compose_jobs_file` and `actual_jobs_services`.

2023-01-17 17:03 UTC, regisb commented on tests/commands/test_compose.py
> +        compose_jobs_file: dict[
Right, let's get rid of them.

2023-01-17 18:54 UTC, Carlos-Muniz commented on tests/commands/test_compose.py
> +        compose_jobs_file: dict[
the type annotations have been removed for both compose_jobs_file and actual_jobs_services.

2023-01-18 06:37 UTC, regisb approved these changes
Thanks for your contribution!

2023-01-18 06:37 UTC, merged

2023-01-18 07:37 UTC, regisb commented
I realized only now that your PR was on the nightly branch. I'll backport the commit to the master branch.