fix: ora2 file upload directory
overhangio/tutor pull request #819
Opened 2023-03-20 20:43 UTC by regisb

ORA2 file uploads were stored in a folder named "SET-ME-PLEASE (ex.
bucket-name)" (sigh). With this change, the folder should be
automatically renamed to "openedxuploads".

This issue has been occuring since June 2019... (sigh²)

Close #707

2023-03-20 20:43 UTC, regisb commented
@sambapete let me know what you think!

2023-03-20 22:55 UTC, sambapete commented
It looks good. Thank @regisb 

I am really grateful that you thought about moving the previous directory to the newest directory. I was wondering if I would have to move things around as we are currently using data/lms/ora2/'SET-ME-PLEASE (ex. bucket-name)' in order to keep things simple while you fixed the issue.

Unfortunately, I will only be able to test it when we begin testing Palm and I can install Palm on my side and migrate my current Olive test server to a Palm test server. Unless of course I try to migrate to Olive again a copy of our current Nutmeg production server.

2023-03-22 13:59 UTC, kdmccormick requested changes
A couple requests, but I think this should work fine (I haven't tested it myself).

Regarding the migration approach, are you sure that doing a destructive system operation in the settings file is the way to go? I don't know of any specific reason that it would be bad; it's just something I've never seen before.

An alternative to consider: change the setting default in Tutor nightly (or even better, edx-platform master!) and add the folder rename to `upgrade_from_olive`.

2023-03-22 13:59 UTC, kdmccormick commented on tutor/templates/apps/openedx/settings/partials/common_all.py
> +deprecated_ora2_folder = os.path.join(ORA2_FILEUPLOAD_ROOT, "SET-ME-PLEASE (ex. bucket-name)")
```suggestion
ora2_folder = os.path.join(ORA2_FILEUPLOAD_ROOT, FILE_UPLOAD_STORAGE_BUCKET_NAME)
# For a long while, we were storing ora2 uploads this directory.
deprecated_ora2_folder = os.path.join(ORA2_FILEUPLOAD_ROOT, "SET-ME-PLEASE (ex. bucket-name)")
```
I would put the comment right above the line that it's referring to.

2023-03-22 13:59 UTC, kdmccormick commented on tutor/templates/apps/openedx/settings/partials/common_all.py
> +if deprecated_ora2_folder != ora2_folder and os.path.exists(deprecated_ora2_folder):
```suggestion
if os.path.exists(deprecated_ora2_folder):
```
This:
> deprecated_ora2_folder != ora2_folder

 will always be true, as the former will always equal `$ORA2_FILEUPLOAD_ROOT/SET-ME-PLEASE (ex. bucket-name)` and the latter `$ORA2_FILEUPLOAD_ROOT/openedxuploads`.

2023-04-28 13:35 UTC, regisb commented
Let's close this. The change will be included in Palm, along with a nice upgrade script.

2023-04-28 13:35 UTC, closed without merging

2023-08-24 08:55 UTC, fghaas commented
Apologies for the incorrect cross-reference to this issue that I made in #896; please disregard.