fix: adds `connect=False` to MongoDB connection configuration
overhangio/tutor pull request #902
Opened 2023-09-26 12:52 UTC by viadanna

## Description

This adds `connect=False` to the LMS and CMS' MongoDB connection configuration to prevent `ServerSelectionError` after a failover.

Related issue: https://github.com/overhangio/tutor/issues/865

2023-09-26 13:27 UTC, regisb requested changes
Thanks for the PR!

1. Can you confirm that this change resolves your issue?
2. Please add a changelog entry with `make changelog-entry` https://docs.tutor.overhang.io/tutor.html#contributing
3. Also, can you add more information in the commit message? It would be great if you could explain why this change is needed.

2023-09-26 13:27 UTC, regisb commented on docs/configuration.rst
> +- ``MONGODB_CONNECT`` (default: ``true``)
Let's not add a new Tutor configuration setting. Instead, we can default to False for everyone. Can you confirm that setting `connect=False` resolves your issue?

2023-10-02 04:45 UTC, regisb commented
Hi @viadanna, your changes look good to me. Can you just please take into account [my comment](https://github.com/overhangio/tutor/pull/902#pullrequestreview-1644267855) above?

2023-10-02 13:56 UTC, viadanna commented
> Hi @viadanna, your changes look good to me. Can you just please take into account [my comment](https://github.com/overhangio/tutor/pull/902#pullrequestreview-1644267855) above?

I changed the behavior and it's running on our development instance; it's still going through an internal review at OpenCraft.

We haven't seen the issue after multiple MongoDB cluster failovers, which was the trigger for the issue in our environments. I'll add a changelog entry and more information to the commit message as soon as it passes our review.

2023-10-02 19:46 UTC, farhaanbukhsh commented
👍 

- ✅ I tested this on the sandbox and this works fine.
- ✅  I read through the code
- ❌  I checked for accessibility issues
- ❌  Includes documentation
- ❌  I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.

2023-10-03 05:01 UTC, regisb commented
In that case, all that is left to do in this PR is to create a changelog entry with `make changelog-entry`: https://docs.tutor.overhang.io/tutor.html#contributing

2023-10-03 17:56 UTC, viadanna commented
@regisb added the changelog and rebased on the last version, let me know if any more changes are required.

2023-10-04 07:43 UTC, regisb commented on changelog.d/20231003_144841_paulo_mongodb_connect.md
> +[Improvement] Adds `connect=False` to the LMS and CMS' MongoDB connection to prevent `ServerSelectionError` after a cluster failover. (by @open-craft)
:ok_hand:

2023-10-04 07:44 UTC, regisb approved these changes
Thanks a lot for experimenting this change! This will be very useful to many users.

2023-10-04 07:48 UTC, merged