fix: wrap django 4 imports in try-except block
overhangio/tutor pull request #958
Opened 2023-12-12 18:04 UTC by mariajgrimaldi

### Description
This PR wraps Django5 warning imports in try-except blocks to avoid failures in django3 that's still in use in edx-platform's master branch. For more info on the report see: https://openedx.slack.com/archives/CGE253B7V/p1702402901252609

2023-12-14 09:41 UTC, regisb commented on tutor/templates/apps/openedx/settings/partials/common_all.py
> +    from django.utils.deprecation import RemovedInDjango50Warning, RemovedInDjango51Warning
Could you please just add a comment that includes the "REMOVE-AFTER-V18" string? and explain why this try/except was still needed in v17.

2023-12-14 09:41 UTC, regisb requested changes
Thanks for the very quick PR! This doesn't require a new release because it fixes the nightly branch (which will automatically get the fix). I'll merge as soon as you add the extra comment.

2023-12-18 14:02 UTC, kdmccormick commented on tutor/templates/apps/openedx/settings/partials/common_all.py
> +    pass
```suggestion
except ImportError:
    # REMOVE-IN-V18:
    # In Quince, edx-platform uses Django 5. But on master, edx-platform still uses Django 3.
    # So, Tutor v17 needs to silence these warnings, whereas Tutor v17-nightly fails to import them.
    # Once edx-platform master is upgraded to Django 5, the try-except wrapper can be removed.
    pass
```

friendly edit -- just adding a REMOVE-IN comment

2023-12-18 21:55 UTC, kdmccormick commented
Merged via https://github.com/overhangio/tutor/commit/aa01e3095d9c7da532a8714e63d7e081dffedbdb

Thanks for the fix @mariajgrimaldi !

2023-12-18 21:55 UTC, closed without merging

2023-12-18 21:57 UTC, kdmccormick commented
@regisb Oof, I just realized I merged this to nightly instead of master 🤦🏻 

I guess that fine, though, since we don't need this change on master? Let me know if you'd rather I make the same change on master too, for consistency's sake.

2023-12-19 08:34 UTC, regisb commented
That's fine, there is no need to backport if the feature is not strictly necessary. But next time, please rebase instead of adding a merge commit.

2023-12-19 15:22 UTC, kdmccormick commented
Will do.